<?php /** @var Twint\Magento\Block\Frontend\ScanQrModal $block */  ?>

<div id="qr-modal-content" style="display: none">
    <div class="to-pay text-20">
        <div class="flex flex-col md:flex-row gap-4 bg-gray-100">
            <!-- Left Column -->
            <div class="default-hidden <?= $block->getMobileClass(); ?> md:flex flex flex-1 order-1 md:order-none bg-white p-4 md:rounded-lg items-center justify-center">
                <div data-twint-copy-token="" class="default-hidden <?= $block->getMobileClass(); ?> md:flex flex flex-col text-center md:flex-col-reverse ">
                    <div class="qr-token text-center my-4 md:mt-6">
                        <input id="qr-token" class="bg-white" type="text" value="" disabled>
                    </div>

                    <div class="md:hidden text-center my-6">
                        <button id="twint-copy"
                                data-clipboard-action="copy"
                                data-clipboard-target="#qr-token"
                                class="p-4 px-6 !bg-white rounded-lg border-black hover:shadow-none hover:border-inherit hover:text-inherit"
                        ><?= __("Copy code"); ?></button>
                    </div>

                    <div class="flex text-center items-center justify-center p-6" id="qrcode">
                    </div>
                </div>
            </div>

            <!-- Right Column -->
            <div class="flex-1 order-0 md:order-1 flex flex-col gap-1 md:gap-4">
                <!-- First Div -->
                <div class="flex flex-1 bg-white p-4 md:rounded-lg items-center justify-center">
                <span id="twint-amount" class=" text-35 inline-block p-4 px-6 text-white bg-black font-semibold">
                    CHF 12.00
                </span>
                </div>
                <!-- Second Div -->
                <div class="flex flex-1 bg-white p-4 md:rounded-lg items-center justify-center">
                    <?= $block->getStoreName(); ?>
                </div>

                <div class="app-selector md:hidden">
                    <?= $block->getLinks(); ?>
                </div>
            </div>
        </div>

        <div class="container mx-auto mt-4 text-16">
            <div id="twint-guides" class="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div class="hidden md:flex md:flex-col items-center p-4">
                    <div class="flex justify-center">
                        <img class="w-55 h-55" src="<?= $block->getViewFileUrl('Twint_Magento/images/icons/icon-scan.svg') ?>" alt="scan">
                    </div>
                    <div class="text-center mt-4"><?= __("Scan this QR Code with your TWINT app to complete the checkout.") ?></div>
                </div>
                <div id="twint-guide-contact" class="hidden flex flex-col items-center p-4">
                    <div class="flex justify-center">
                        <img class="w-55 h-55" src="<?= $block->getViewFileUrl('Twint_Magento/images/icons/icon-contact.svg') ?>" alt="contact">
                    </div>
                    <div class="text-center mt-4"><?= __("Follow the instructions in the app to confirm your order.") ?></div>
                </div>
            </div>
        </div>
    </div>

    <div class="on-success p-6">
        <h1><?= __("Thank you for your purchase!"); ?></h1>
        <p>
            <?= __("Your order # is: <span>%1</span>."); ?>
        </p>
        <p>
            <?= __("We'll email you an order confirmation with details and tracking info."); ?>
        </p>
    </div>
</div>

<div id="twint-loading">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 200 200" shape-rendering="geometricPrecision" text-rendering="geometricPrecision">
        <g transform="matrix(.72509 0 0-.72509 12.626655 199.33733)">
            <path d="M125.9,268.725c0,0,105.6-61,105.6-61c3-1.7,5.4-5.9,5.4-9.4c0,0,0-122,0-122c0-3.4-2.4-7.7-5.4-9.4c0,0-105.6-61-105.6-61-3-1.7-7.9-1.7-10.9,0c0,0-105.6,61-105.6,61-3,1.7-5.4,6-5.4,9.4c0,0,0,122,0,122c0,3.4,2.4,7.7,5.4,9.4c0,0,105.6,61,105.6,61c3,1.7,7.9,1.7,10.9,0Z"
                  paint-order="stroke fill markers" fill="none" fill-rule="evenodd" stroke="#dfdfdf" stroke-width="10" stroke-linecap="round" stroke-linejoin="round"/>
        </g>
        <g transform="matrix(.72509 0 0-.72509 12.626655 199.33733)">
            <path id="twintAnimation" stroke-linecap="round" stroke-linejoin="round" fill-opacity="0" stroke="rgb(38,38,38)" stroke-opacity="1" stroke-width="10" d="M0 0"></path>
        </g>
    </svg>
</div>

