image: shivammathur/node:jammy

variables:
  COMPOSER_ALLOW_SUPERUSER: "1"
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: magento2_test

stages:
  - check
  - release

.base:
  before_script:
    - set -euo pipefail
  tags:
    - d13-runner

test:
  only:
    - merge_requests
    - master
    - staging
  extends: .base
  stage: check
  parallel:
    matrix:
      - MAGENTO_VERSION: [ "2.4.6" ]
        PHP_VERSION: [ "8.1", "8.2" ]
      - MAGENTO_VERSION: [ "2.4.7" ]
        PHP_VERSION: [ "8.1", "8.2", "8.3" ]
  services:
    - mysql:8.0
    - name: elasticsearch:7.17.22
      alias: elasticsearch
      command: [ "elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node", "-Expack.license.self_generated.type=basic" ]
  variables:
    ELASTIC_PASSWORD: e_password
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
   
  script:
    # Update spc (See https://github.com/shivammathur/spc for options)
    - spc -U

    # Setup PHP
    - spc --php-version "$PHP_VERSION" --extensions "bcmath, ctype, curl, dom, fileinfo, filter,gd, hash, iconv, intl, json, libxml, mbstring, openssl, pcre, pdo_mysql, simplexml, soap, sockets, sodium, xsl, tokenizer, xmlwriter, xsl, zlib, libxml"
  
    - composer config repositories.twint-sdk vcs https://git.nfq.asia/twint-ag/php-sdk.git
    - composer config --global http-basic.repo.magento.com $MAGENTO_PUBLIC $MAGENTO_PRIVATE
    - composer config --global gitlab-token.git.nfq.asia $GITLAB_ACCESS_TOKEN

    # Install dependencies for plugin itself
    - |
      rm -f composer.lock
      composer config prefer-stable true
      composer config minimum-stability dev
      composer install --prefer-dist --no-progress --no-interaction

    # Run coding standard
    - ./vendor/bin/ecs --no-progress-bar
    - vendor/bin/rector process --dry-run

    # Checkout Magento Community template, and change working directory to magento root folder
    - composer create-project --repository-url=https://repo.magento.com/
      magento/project-community-edition=$MAGENTO_VERSION magento > /dev/null
    - cd magento

    - |
      composer config prefer-stable true
      composer config minimum-stability dev
      composer config repositories.twint-sdk vcs https://git.nfq.asia/twint-ag/php-sdk.git
      composer config repositories.twint-extension vcs git@git.nfq.asia:twint-ag/twint-magento-extension.git
    - |
      rm -f composer.lock
      composer install --prefer-dist --no-progress --no-interaction

    # Make sure elastic search is ready
    - |
      until curl -s -X GET "http://elasticsearch:9200/_cluster/health" > /dev/null; do
        echo 'Waiting for Elasticsearch to be ready...'
        sleep 5
      done

    - bin/magento setup:install --base-url=http://127.0.0.1/magento2/ --db-host=mysql --db-name=$MYSQL_DATABASE --db-user=root --db-password=$MYSQL_ROOT_PASSWORD --language=en_US --currency=USD  --timezone=America/Chicago --use-rewrites=1 --search-engine=elasticsearch7  --elasticsearch-enable-auth=1 --elasticsearch-host=http://elasticsearch --elasticsearch-username=elastic  --elasticsearch-password=e_password  --elasticsearch-index-prefix=magento2 > /dev/null
  
    - composer require twint-ag/twint-magento-extension:dev-$CI_COMMIT_REF_NAME --no-update
    - |
      rm -f composer.lock
      composer install --prefer-dist --no-progress --no-interaction
  
    # Remove zinfra folder to avoid issue during di compile
    - rm -rf vendor/twint-ag/twint-magento-extension/zinfra

    - bin/magento cache:clean && bin/magento cache:flush > /dev/null

    - bin/magento module:enable Twint_Magento
    - bin/magento setup:upgrade | grep Twint
    - bin/magento setup:di:compile > /dev/null
#    - bin/magento setup:static-content:deploy -f > /dev/null

  cache:
    key: $CI_COMMIT_REF_SLUG-${CI_JOB_NAME}
    paths:
      - $CI_PROJECT_DIR/.gitlab-ci-cache

release:
  only:
    - tags
  stage: release
  image: alpine:3
  extends: .base
  variables:
    GIT_DEPTH: 0
  script:
    - apk add --no-cache git openssh bash
    - ./utils/sync.sh
