<?php
/** @var View $block */

use Twint\Magento\Block\Adminhtml\Pairing\View;

if(!$block->isExpress()){
    echo "<h2>" .__("Refund history") ."</h2>";
    echo $block->getChildHtml('twint.grid.refund_history.container');

    echo "<h2>" .__("Transaction history") ."</h2>";
    echo $block->getChildHtml('twint.grid.pairing_history.container');
}else{
    echo "<h2>" .__("Transaction history") ."</h2>";
    echo $block->getChildHtml('twint.grid.pairing_express_history.container');
}
