<?php

declare(strict_types=1);

namespace Twint\Magento\Provider\Data;

use Magento\Framework\Api\FilterBuilder;
use Magento\Framework\Api\Search\ReportingInterface;
use Magento\Framework\Api\Search\SearchCriteriaBuilder;
use Magento\Framework\App\RequestInterface;
use Magento\Framework\View\Element\UiComponent\DataProvider\DataProvider;
use Magento\Sales\Api\OrderRepositoryInterface;

class PairingHistoryDataProvider extends DataProvider
{
    public function __construct(
        private readonly OrderRepositoryInterface $repository,
        $name,
        $primaryFieldName,
        $requestFieldName,
        ReportingInterface $reporting,
        SearchCriteriaBuilder $searchCriteriaBuilder,
        RequestInterface $request,
        FilterBuilder $filterBuilder,
        array $meta = [],
        array $data = [],
    ) {
        parent::__construct($name, $primaryFieldName, $requestFieldName, $reporting, $searchCriteriaBuilder, $request, $filterBuilder, $meta, $data);
    }

    public function addFilter(\Magento\Framework\Api\Filter $filter)
    {
        if( $filter->getField() == 'id'){
            $filter->setField('parent_id');
        }

        parent::addFilter($filter); // TODO: Change the autogenerated stub
    }
}
