<?php /** @var Button $block */

use Twint\Magento\Block\Frontend\Express\Button; ?>

<button type="submit" disabled class="tw-button express pdp">
    <span class="tw-icon-block">
        <img class="tw-icon" src="<?= $block->getViewFileUrl('Twint_Magento/images/express.svg') ?>" alt="Express Checkout">
    </span>
    <span class="tw-label"><?php echo __("Express Checkout"); ?></span>
</button>
