<?php /** @var \Twint\Magento\Block\Frontend\Express\Button $block */  ?>

<button disabled class="twint-button express cart mini mt-4 w-full"
        data-mage-init='{"Twint_Magento/js/express/cart-checkout":{}}'>
    <span class="icon-block">
        <img class="twint-icon" src="<?= $block->getViewFileUrl('Twint_Magento/images/express.svg') ?>" alt="Express Checkout">
    </span>
    <span class="twint-label"><?php echo __("Express Checkout"); ?></span>
</button>
